### PR TITLE
New feature: Client side form validation on login and signup form

### PR DESCRIPTION
**Pull request by 1Fetcher**
## Related Issue 

- Client side validation during login and sign up added.

- [x] Hacktoberfest Participant 
- [ ] Contributor

Closes: #17

### Describe the changes you've made

If user submit form during signup or login without filling the form it will display validation errors. 

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Just submit the signup or login form without filling the form. 

## Checklist:
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 image | image  |
 image | image  |

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
First create an issue, add issue template, include issue details, be specific about the issue you are willing to work on to get it assigned. Never do PR without getting an issue assigned. @1Fetcher

**Comment by 1Fetcher** [comment]
> First create an issue, add issue template, include issue details, be specific about the issue you are willing to work on to get it assigned. Never do PR without getting an issue assigned. @1Fetcher

Thanks for the guidance, I have created an issue please check and assign it to me.

**Comment by prathimacode-hub** [comment]
Now follow the same process. Add the PR template here above in your commit message with issue details and issue number assigned for the PR to be reviewed. @1Fetcher

**Comment by 1Fetcher** [comment]
> Now follow the same process. Add the PR template here above in your commit message with issue details and issue number assigned for the PR to be reviewed. @1Fetcher

DONE (:

**Review by prathimacode-hub — APPROVED** [review]
PR approved. 👌✔@1Fetcher

**Pull request merged**
