### PR TITLE
Created testimonial section for home page

### LINKED ISSUE #9: Ezy-Parking : Create the Testimonials section for the Home Page
Hey Hacktoberfest participants, good to see you.

This issue's goal is to add the testimonial section to the home page in an appealing format for Ezy-Parking Webapp .

Feel free to be creative! And please take care of the following criteria:

- create atleast 6 dummy testimonials that slides up continuously with separate section of testimonials created in the home page before to Frequently Asked Questions. 
- Try and get the structure approved before making final pr.

How to get it approved?

- Add a screenshot of testimonial section created in video format on this thread and wait for one of the mentors to get back to you.
- Once it's approved, go ahead and make pr.

Please read [CONTRIBUTING.md](https://github.com/prathimacode-hub/Ezy-Parking/blob/main/CONTRIBUTING.md) at least once before contributing code.

### PR DESCRIPTION
**Pull request by Nincompup**
Fixes #9 as follows : 

## Related Issue 

- Issue is about to create testimonial section for home page in given website

- [x] Hacktoberfest Participant  
- [ ] Contributor

Closes: #9 

### Description of changes made

Added testimonial section containing 6 dummy testimonials with the help of slider as shown in video below :

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

It has been tested through simulation and also through Hardware ESP32

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

https://user-images.githubusercontent.com/114563503/193516245-44901def-6a0c-4b77-8f55-8954b78be43b.mp4

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Add a PR template, include the issue details you had worked on, add issue number for it to be reviewed. @Nincompup

**Comment by Nincompup** [comment]
I have made pull request templte

**Comment by Nincompup** [comment]
Added a pr template as commit @prathimacode-hub

**Comment by prathimacode-hub** [comment]
I had added the format, now give the description in the this PR commit message. @Nincompup

**Comment by prathimacode-hub** [comment]
> I have made pull request template

Don't add as separate PR. I already added the format, add the description. This is how a PR should be created. @Nincompup

**Comment by Nincompup** [comment]
@prathimacode-hub is it okay now ?

**Comment by Nincompup** [comment]
Gentle Reminder !
@prathimacode-hub 

> @prathimacode-hub is it okay now ?

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Well done.👍✔@Nincompup

**Pull request merged**
