### PR TITLE
DOCKERIZE THE WEB APP 🛠

### PR DESCRIPTION
**Pull request by IshanSingla**
Feature : Dockerize the web app 🛠

 * added dockerfile in frontend web app

### CODE REVIEW

**Review by prathimacode-hub — COMMENTED** [review]
I don't think this is needed now. @IshanSingla

**Comment by prathimacode-hub** [comment]
Come up with new issue and create an issue template to get it assigned before you start working. Follow the contributing guidelines given. @IshanSingla

**Comment by IshanSingla** [comment]
I think docker is required for a stable build in any custom server @prathimacode-hub

**Comment by prathimacode-hub** [comment]
First create an issue and elaborate the issue details to know if it's needed or not. @IshanSingla

**Pull request closed without merging**
